
  CREATE TABLE "SHANGLIWEI"."S_T_EMPLOYEE" 
   (	"ID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"SEQUENCE" NUMBER(*,0), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"STATE" VARCHAR2(2 BYTE), 
	"DEPARTMENT_ID" VARCHAR2(32 BYTE), 
	"CREATER" VARCHAR2(32 BYTE), 
	"CREATTIME" TIMESTAMP (6), 
	"EDITER" VARCHAR2(32 BYTE), 
	"EDITTIME" TIMESTAMP (6), 
	 CONSTRAINT "S_T_EMPLOYEE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
  CREATE TABLE "SHANGLIWEI"."S_T_DEPARTMENT" 
   (	"ID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE), 
	"PARENT_ID" VARCHAR2(32 BYTE), 
	"TYPE" VARCHAR2(2 BYTE), 
	"MANAGER" VARCHAR2(32 BYTE), 
	"STATE" VARCHAR2(2 BYTE), 
	"CREATE_DATE" DATE, 
	"CLOSE_DATE" DATE, 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"CREATER" VARCHAR2(32 BYTE), 
	"CREATTIME" TIMESTAMP (6), 
	"EDITER" VARCHAR2(32 BYTE), 
	"EDITTIME" TIMESTAMP (6), 
	 CONSTRAINT "S_T_DEPARTMENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

  
  CREATE TABLE "SHANGLIWEI"."S_T_DICTIONARY" 
   (	"ID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"CODE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"SORT" NUMBER, 
	"EFFECTIVE" VARCHAR2(2 BYTE), 
	"CREATER" VARCHAR2(32 BYTE), 
	"CREATTIME" TIMESTAMP (6), 
	"EDITER" VARCHAR2(32 BYTE), 
	"EDITTIME" TIMESTAMP (6), 
	 CONSTRAINT "S_T_DICTIONARY_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
